from sys import argv
import os
import re
import time
import multiprocessing
import numpy as np
import pandas as pd
import math

wt = 'AGTAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTGATGTTAATGGGCACAAATTTTCTGTCAGTGGAGAGGGTGAAGGTGATGCAACATACGGAAAACTTACCCTTAAATTTATTTGCACTACTGGAAAACTACCTGTTCCATGGCCAACACTTGTCACTACTTTCACTTATGGTGTTCAATGCTTTTCAAGATACCCAGATCATATGAAACGGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTACAGGAAAGAACTATATTTTTCAAAGATGACGGGAACTACAAGACACGTGCTGAAGTCAAGTTTGAAGGTGATACCCTTGTTAATAGAATCGAGTTAAAAGGTATTGATTTTAAAGAAGATGGAAACATTCTTGGACACAAATTGGAATACAACTATAACTCACACAATGTATACATCATGGCAGACAAACAAAAGAATGGAATCAAAGTTAACTTCAAAATTAGACACAACATTGAAGATGGAAGCGTTCAACTAGCAGACCATTATCAACAAAATACTCCAATTGGCGATGGCCCTGTCCTTTTACCAGACAACCATTACCTGTCCACACAATCTGCCCTTTCGAAAGATCCCAACGAAAAGAGAGACCACATGGTCCTTCTTGAGTTTGTAACAGCTGCTGGGATTACACATGGCATGGATGAACTATACAAA'

infile,outfile=argv[1:]
out = open(outfile,"w")
with open(infile,'r') as file1:
    for line in file1:
        misfolding_value = line.split(' ')[1]
        seq = line.split(' ')[5]
        for i in range(687):
            if seq[i] != wt[i]:
                out.write(wt[i] + str(i+4) + seq[i] + ',' + misfolding_value + '\n')

out.close()

pdb = 'MSKATYKERAATHPSPVAAKLFNIMHEKQTNLCASLDVRTTKELLELVEALGPKICLLKTHVDILTDFSMEGTVKPLKALSAKYNFLLFEDRKFADIGNTVKLQYSAGVYRIAEWADITNAHGVVGPGIVSGLKQAAEEVTKEPRGLLMLAELSCKGSLATGEYTKGTVDIAKSDKDFVIGFIAQRDMGGRDEGYDWLIMTPGVGLDDKGDALGQQYRTVDDVVSTGSDIIIVGRGLFAKGRDAKVEGERYRKAGWEAYLRRCGQQN'
aaa = 'MSTKSYTSRAETHASPVASKLLRLMDEKKTNLCASLDVRSTDELLKLVETLGPYICLLKTHVDILDDFSYEGTVVPLKALAEKYKFLIFEDRKFADIGNTVKLQYTSGVYRIAEWSDITNAHGVTGAGIVAGLKQGAQEVTKEPRGLLMLAELSSKGSLAHGEYTKGTVDIAKSDKDFVIGFIAQNDMGGREEGFDWLIMTPGVGLDDKGDALGQQYRTVDEVVSGGSDIIIVGRGLFAKGRDPKVEGERYRNAGWEAYQKRISAPH'

for i in range(267):
    if pdb[i] != aaa[i]:
        print(pdb[i] + str(i) + aaa[i])

