from sys import argv

ccs_file,=argv[1:]

ccsfile = open(ccs_file,"r")
wt = "ATGAGTAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTGATGTTAATGGGCACAAATTTTCTGTCAGTGGAGAGGGTGAAGGTGATGCAACATACGGAAAACTTACCCTTAAATTTATTTGCACTACTGGAAAACTACCTGTTCCATGGCCAACACTTGTCACTACTTTCACTTATGGTGTTCAATGCTTTTCAAGATACCCAGATCATATGAAACGGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTACAGGAAAGAACTATATTTTTCAAAGATGACGGGAACTACAAGACACGTGCTGAAGTCAAGTTTGAAGGTGATACCCTTGTTAATAGAATCGAGTTAAAAGGTATTGATTTTAAAGAAGATGGAAACATTCTTGGACACAAATTGGAATACAACTATAACTCACACAATGTATACATCATGGCAGACAAACAAAAGAATGGAATCAAAGTTAACTTCAAAATTAGACACAACATTGAAGATGGAAGCGTTCAACTAGCAGACCATTATCAACAAAATACTCCAATTGGCGATGGCCCTGTCCTTTTACCAGACAACCATTACCTGTCCACACAATCTGCCCTTTCGAAAGATCCCAACGAAAAGAGAGACCACATGGTCCTTCTTGAGTTTGTAACAGCTGCTGGGATTACACATGGCATGGATGAACTATACAAATAGGGCGCGCCACTTCTAA"
ccs_dict = {}
for every in ccsfile:
    if len(every)>30:
        geno = every.strip().split(",")[1]
        umi = every.strip().split(",")[2]
        ccs_dict[umi] = geno

umi_num = len(ccs_dict)
single_num = 0
for line in ccs_dict:
    mut_num = 0
    line_geno = ccs_dict[line]
    for i in range(733):
        if line_geno[i] != wt[i]:
            mut_num += 1
    if mut_num == 1:
        single_num += 1

print("The total number is" + str(umi_num))
print("The number of single is " + str(single_num))

ccsfile.close()